[[main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    weight = 1

[[main]]
    identifier = "writings"
    name = "Writings"
    url = "/writings"
    weight = 2

# [[main]]
#     identifier = "projects"
#     name = "Projects"
#     url = "/projects"
#     weight = 3

[[main]]
    identifier = "readings"
    name = "Readings"
    url = "/readings"
    weight = 4

[[main]]
    identifier = "activities"
    name = "Activites"
    url = "/activities"
    weight = 5

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 7

# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/javierdlrm"
    weight = 2

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/javierdlrm"
    weight = 1

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/javierdlrm/"
    weight = 2
